# Fancy Physics sounds like for block crack
Sounds: true
SpawnPhysicsProtection:
  Enabled: false
  RadiusInBlocks: 50
  Location:
    world: "world"
    x: 1
    y: 1
    z: 1
Explosion:
  Physics: true
  NaturalDrops: true
EntityDeathParticles: true
# Block break particles
Particle:
  Enabled: true
  Animation:
    # Rotate the particles
    Rotation: true
    # Blocks will just fly up and get smaller when broken
    FlyUp: false
    SpeedInTicks: 40
    EndSizeMultiplier: 0.5
  # How many particles can exist at once on the entire server
  MaxAmount: 4000
DamageParticles: true
PerformanceMode: true
Tree:
  Physics: true
  DropSaplings: true
  # This adds like multiple stages to the broken block to make it longer to fell a tree
  ChopDelay: true
  # If true a tree will fall on the ground if a block was broken below it
  GravityIfInAir: true
  # Adds all the broken blocks of a tree when fallen to the players stats
  AffectedBlocksInPlayerBreakBlocksStatistic: true
  AdvancedStemScan: false
  ScanMaxStemSize: 200
  ScanMaxLeavesSize: 260
  MaxInvalidScans: 2700
  MaxInvalidBlockDistance: 2
# Displays the currently used items in a crafting table above the actual block (One player limit)
VisualCrafting: true
# Breaks all blocks when falling
FallingBlockPhysics: true
# Adds the particle animation to blocks which fall
BlockCrackOnFall: true
# Adds a small opening and closing animation to trapdoors.. Just use this for testing not on a production server
TrapdoorPhysics: false
# When sprinting against glass or a door it will break
SprintBreak:
  Door: false
  Glass: false
# Regenerate certain blocks or trees when destroyed after a specific delay
Regeneration:
  TreeRegeneration:
    Enabled: false
    Delay: 10
  ExplosionRegeneration:
    Enabled: false
    Delay: 10
# There will be no particles for the following blocks when broken
BlockParticleBlackList:
  - END_ROD
  - POINTED_DRIPSTONE
  - CANDLE
  - BLACK_CANDLE
  - CYAN_CANDLE
  - GRAY_CANDLE
  - LIGHT_GRAY_CANDLE
  - BAMBOO
  - PURPLE_CANDLE
  - BLUE_CANDLE
  - LIME_CANDLE
  - RED_CANDLE
  - WHITE_CANDLE
  - PINK_CANDLE
  - MAGENTA_CANDLE
  - BROWN_CANDLE
  - GRAY_CANDLE
  - GREEN_CANDLE
  - YELLOW_CANDLE
  - ORANGE_CANDLE
  - RED_CANDLE
  - LIGHT_BLUE_CANDLE
  - CHAIN
  - GRASS
  - DANDELION
  - CRIMSON_FUNGUS
  - WARPED_FUNGUS
  - OXEYE_DAISY
  - WITHER_ROSE
  - ORANGE_TULIP
  - RED_TULIP
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - TALL_GRASS
  - SCULK_VEIN
  - CHERRY_SAPLING
  - LARGE_FERN
  - SUNFLOWER
  - CORNFLOWER
  - PINK_PETALS
  - TORCHFLOWER
  - MANGROVE_PROPAGULE
  - TWISTING_VINES
  - POPPY
  - ALLIUM
  - PINK_TULIP
  - LILY_OF_THE_VALLEY
  - BLUE_ORCHID
  - WARPED_ROOTS
  - AZURE_BLUET
  - BAMBOO
# In these worlds no physics will be applied
DisabledWorldsList:
  - DisabledWorld
  - AnotherDisabledWorld